name: undede
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_callkit_incoming: ^2.0.4+2
  carousel_slider: ^5.0.0
  animated_splash_screen: ^1.3.0
  get: ^4.6.6
  http: ^1.2.2
  flutter_multi_formatter: ^2.13.0
  shared_preferences: ^2.3.4
  persistent_bottom_nav_bar: ^6.2.1
  firebase_core: ^3.9.0
  path_provider: ^2.1.5
  file_picker: ^8.1.6
  flutter_plugin_android_lifecycle: ^2.0.24
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  awesome_notifications: ^0.10.0 # baska bir notification ile kullanma. flutter_local_notifications gibi.API sorunu var
  flutter_rating_bar: ^4.0.1
  awesome_dialog: ^3.2.1
  awesome_notifications_core: ^0.10.0
  url_launcher: ^6.3.1
  socket_io_client: ^3.0.2
  package_info_plus: ^8.1.2
  share_plus: ^10.1.3 # share eklentisi yeni adi ile share_plus
  flutter_colorpicker: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0 # depräcated oldu yerine flutter_datetime_picker_plus eklendi
  dropdown_search: ^6.0.2
  fluttertoast: ^8.2.10
  rflutter_alert: ^2.0.7
  infinite_scroll_pagination: ^4.1.0
  flutter_pagewise: ^2.0.4
  intl_phone_number_input: ^0.7.4
  bubble_tab_indicator: ^0.1.6
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^5.2.0
  image_cropper: ^8.1.0
  flutter_speed_dial: ^7.0.0
  uuid: ^4.5.1
  we_slide: ^2.4.0
  sliding_up_panel: ^2.0.0+1
  sliding_sheet2: ^2.0.1 # sliding_sheet eklentisi yeni adi ile sliding_sheet2 olarak degistirildi 2.0.1 surumu
  cached_network_image: ^3.4.1
  flutter_sound: ^9.6.0 #flutter_sound_lite: 8.5.0 iptal edildi yerine flutter_sound eklendi
  photo_view: ^0.15.0
  custom_pop_up_menu: ^1.2.4
  flutter_tags_x: ^1.1.0  #flutter_tags: ^0.4.9+1 iptal edildi yerine flutter_tags_x eklendi
  modal_progress_hud_nsn: ^0.5.1 #modal_progress_hud: 0.1.3 iptal edildi yerine modal_progress_hud_nsn eklendi
  scrollable_positioned_list: ^0.3.8
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^8.0.1
  dio: ^5.7.0
  percent_indicator: ^4.2.4
  shimmer: ^3.0.0
  camera: ^0.11.0+2 #//TODO: Bunun  bayi ayarlari var uunutma.
  permission_handler: ^11.3.1 #//TODO: Bunun  bayi ayarlari var uunutma.
  font_awesome_flutter: ^10.8.0 #//TODO: Bunun  bayi ayarlari var uunutma.
  string_validator: ^1.1.0
  image: ^4.5.2
  firebase_messaging: ^15.1.6
  syncfusion_flutter_charts: ^28.1.36
  syncfusion_flutter_pdf: ^28.1.36
  syncfusion_localizations: ^28.1.36
  syncfusion_flutter_pdfviewer: ^28.1.36
  syncfusion_flutter_calendar: ^28.1.36
  currency_text_input_formatter: ^2.2.6 #cakisma olursa asagidaki kodu ekle #dependency_overrides: #intl: your intl package version  
  rive: ^0.13.20
  translator: ^1.0.3+1
  open_filex: ^4.6.0
  signature: ^5.5.0
  flutter_inappwebview: ^6.1.5
  exprollable_page_view: ^1.0.1
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^3.1.2
  flutter_pdfview: ^1.3.4
  flutter_widget_from_html: ^0.15.3
  flutter_tree: ^2.0.3
  overlay_loader_with_app_icon: ^0.0.4
  restart_app: ^1.3.2
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  html_editor_enhanced: ^2.6.0
  flutter_localizations:
    sdk: flutter
  palette_generator: ^0.3.3+5
  motion_tab_bar_v2: ^0.3.0
  iconly: ^1.0.1
  crystal_navigation_bar: ^1.0.2
  animated_notch_bottom_bar: ^1.0.3
  floating_bottom_navigation_bar: ^1.5.2
  simple_circular_progress_bar: ^1.0.2
  flutter_floating_bottom_bar: ^1.2.1+1
  ionicons: ^0.2.2
  animated_tree_view: ^2.3.0
  tree_view: ^0.0.6
  flutter_tree_pro: ^0.0.14
  board_datetime_picker: ^2.5.0
  expandable_richtext: ^1.0.7
  flutter_html: ^3.0.0
  selectable_search_list: ^0.0.2
  flutter_selectable_list: ^0.0.10
  expansion_tile_card: ^3.0.0

 

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo/logonew.png"
  min_sdk_android: 21
#flutter_icons:
 # android: true
  #ios: true
  #image_path: "assets/images/app_logo/logobeyaz.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/icon/
    - assets/images/
    - assets/images/app_logo/
    - assets/images/file_types/
    - assets/splash/
    - assets/splash/0.png
    - assets/images/OTPGif/
    - assets/fonts/
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  fonts:
    - family: TTNorms
      fonts:
        - asset: assets/fonts/TTNormsPro-Regular.ttf
          weight: 100
        - asset: assets/fonts/TTNormsPro-Medium.ttf
          weight: 500
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
